### ISSUE TITLE
TrackedResourcePatchOperation does not consider 201 responses

### ISSUE THREAD

**Issue by dsgouda** [Azure/azure-openapi-validator#109]
TrackedResourcePatchOperation must consider `201` responses when validating whether tracked resources have a corresponding PATCH operation.
Needs a fix [here](https://github.com/Azure/azure-openapi-validator/blob/master/src/dotnet/OpenAPI.Validator/Validation/TrackedResourcePatchOperation.cs#L69) .
P.S.: Add a test case with `201` status code

**Comment by sarangan12** [comment]
Closing this issue in favor of https://github.com/Azure/azure-openapi-arm-validator/issues/10
