### ISSUE TITLE
XmsPathsMustOverloadPaths - check looks at exact match and does not consider variables in path

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-openapi-validator#117]
For example, paths like "/{roleDefinitionID}" and "/{roleAssignmentId}" (from [authorization spec](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/authorization/resource-manager/Microsoft.Authorization/2015-07-01/authorization.json)) are equivalent, and needed disambiguation via x-ms-paths, however they are not related and exact string comparison does not find them to be the same, as they are using variables. 
The rule may need to consider/ignore anything between braces {}.

**Comment by veronicagg** [comment]
https://github.com/Azure/azure-openapi-validator/issues/130

**Comment by sarangan12** [comment]
Tracked by https://github.com/Azure/azure-openapi-validator/issues/130. CLosing this
