### ISSUE TITLE
Supressing Warning Leads to other warning in some cases

### ISSUE THREAD

**Issue by salameer** [Azure/azure-openapi-validator#118]
When the service fabric team suppresses R2066 - this is the output I get:

WARNING:Could not find the exact path ["paths","/$/GetClusterHealth","post","GetClusterHealthUsingPolicy"] for "OperationId should contain the verb: '/$/getclusterhealth' in:'GetClusterHealthUsingPolicy'. Consider updating the operationId"
WARNING (PostOperationIdContainsUrlVerb/R2066/SDKViolation): OperationId should contain the verb: '/$/getclusterhealth' in:'GetClusterHealthUsingPolicy'. Consider updating the operationId
    - file:///C:/temp/sfclient-spec/servicefabric.json:95:6 ($.paths["/$/GetClusterHealth"].post)

If I suppress R0266, I get the following:
WARNING:Couldnot find the exact path ["paths","/$/GetClusterHealth","post","GetClusterHealthUsingPolicy"] for "OperationId should contain the verb: '/$/getclusterhealth' in:'GetClusterHealthUsingPolicy'. Consider updating the operationId"

**Comment by salameer** [comment]
@VipulM-MSFT as FYI.

Hi Vipul this is where you can track the warning suppresion issue that you reported below

THanks,

Samer

**Comment by veronicagg** [comment]
The issue with autorest showing these warnings was addressed with https://github.com/Azure/autorest/commit/668aabe2a3c790452773b06223cfd81d9d3e9649 If you're still seeing this issue, please let us know. thanks!
