### ISSUE TITLE
Validator should error if spec describes more than one resource provider

### ISSUE THREAD

**Issue by devigned** [Azure/azure-openapi-validator#121]
If a spec references another provider, the validator should throw an error. This would imply the resource providers have a dependency relationship for a particular api-version. This will impact the ability for generated code to properly target hybrid cloud.

For example, Key Vault references the Resources RP to list all resources within a subscription, rather than exposing this operation through their RP.

See: https://github.com/Azure/azure-rest-api-specs/blob/current/specification/keyvault/resource-manager/Microsoft.KeyVault/2016-10-01/keyvault.json#L294-L342

**Comment by veronicagg** [comment]
@devigned Is the rule that you're referring to https://github.com/Azure/azure-openapi-validator/blob/master/src/dotnet/OpenAPI.Validator/Validation/UniqueResourcePaths.cs ?
If so, based on what you mentioned, seems that it may need to be enhanced, is there a good way we can detect the case above?

**Comment by devigned** [comment]
Hmm... This validation rule should have caught this. Do you think this spec was accepted before that rule was running?

**Comment by devigned** [comment]
I would imagine this should be triggered by anything that has a hardcoded api version specified like here: https://github.com/Azure/azure-rest-api-specs/blob/d2bb2feadd0deb1c7212706aa65cab2f56adccc7/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2016-10-01/keyvault.json#L318-L323 and if there is a different provider uri in one of the paths (https://github.com/Azure/azure-rest-api-specs/blob/d2bb2feadd0deb1c7212706aa65cab2f56adccc7/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2016-10-01/keyvault.json#L294 vs https://github.com/Azure/azure-rest-api-specs/blob/d2bb2feadd0deb1c7212706aa65cab2f56adccc7/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2016-10-01/keyvault.json#L254).

Does this make sense?

**Comment by sarangan12** [comment]
Closing this issue in favor of https://github.com/Azure/azure-openapi-arm-validator/issues/9
