### ISSUE TITLE
Supporting New Batch of  ARM & SDK  Linter Rules

### ISSUE THREAD

**Issue by salameer** [Azure/azure-openapi-validator#124]
Before We Start @ravbhatnagar, we'll need to the list and description following the same format that we have on rules wiki

**Comment by veronicagg** [comment]
@salameer this issue does not have any details, could we close it and have one opened if/when details are available?

**Comment by vladbarosan** [comment]
@salameer is this still relevant  or any details on what is the new batch of rules ?

**Comment by salameer** [comment]
Nope, let's remove this and go with one issue per rule and schedule them when required

**Comment by vladbarosan** [comment]
Ok thanks, closing this.
