### ISSUE TITLE
Inline definitions

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-openapi-validator#125]
Will there be a rule that complains when there is stuff defined inline instead of the definitions section in the swagger?

**Comment by veronicagg** [comment]
Is this what you're looking for: https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#r2024-anonymousbodyparameter ?
If so, yes, we have a rule for it and should be triggering as appropriate. 
I'm closing the issue based on this, feel free to reopen if this doesn't answer your question.

**Comment by mcardosos** [comment]
Cool!
