### ISSUE TITLE
Camel casing rule should be clarified to prevent confusion

### ISSUE THREAD

**Issue by olydis** [Azure/azure-openapi-validator#138]
We often see service teams adjust their Swaggers according to the rule, causing it to no longer match their service. Most of the time it is not clear to them that 100% reflecting the service (case sensitively!) is top priority. So really, the rule is complaining about how the service looks like (something that should have been caught during API review).

We should clarify that the rule is about the API and nothing is solved by simply adjusting the Swagger.

**Comment by veronicagg** [comment]
@kirthik could you weight in on this messaging? we could update the message for the rule, but there's also a general message for teams on how they should act on validation errors. 
Which message would be better? our current rule is specified as follows - https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#r3014-bodypropertiesnamescamelcase

**Comment by sarangan12** [comment]
Closing this issue in favor of https://github.com/Azure/azure-openapi-arm-validator/issues/8
