### ISSUE TITLE
Discriminators are not accounted for in rules

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-openapi-validator#139]
For example - spec https://github.com/Azure/azure-rest-api-specs/blob/master/specification/timeseriesinsights/resource-manager/Microsoft.TimeSeriesInsights/stable/2017-11-15/timeseriesinsights.json

2.	(TrackedResourceGetOperation/R3025/RPCViolation): Tracked resource 'EventHubEventSourceResource' must have a get operation.
3.	(TrackedResourceGetOperation/R3025/RPCViolation): Tracked resource 'IoTHubEventSourceResource' must have a get operation.
4.	(TrackedResourcePatchOperation/R3026/RPCViolation): Tracked resource 'EventHubEventSourceResource' must have patch operation that at least supports the update of tags. It's strongly recommended that the PATCH operation supports update of all mutable properties as well.
5.	(TrackedResourcePatchOperation/R3026/RPCViolation): Tracked resource 'IoTHubEventSourceResource' must have patch operation that at least supports the update of tags. It's strongly recommended that the PATCH operation supports update of all mutable properties as well.

The above are tracked resources and have the corresponding operations defined for their parent, the models referred to above are discriminators, which are not being accounted for. 
Other rules may be affected by this too, as I don't think we're accounting for discriminators in our logic to check for models/resources.

**Comment by veronicagg** [comment]
@salameer This is a change to the logic on resources detection and accounting for discriminators. The rules affected above are RPC violations, but it may be affecting any other rule that relies on our Resource identification.  Should probably be at least evaluated in the next sprint, to see if we want to pursue the change or not.

**Comment by sarangan12** [comment]
Closing this issue as a new one is opened at https://github.com/Azure/azure-openapi-arm-validator/issues/7
