### ISSUE TITLE
Upnublish the azure-openapi-linter package from npm

### ISSUE THREAD

**Issue by dsgouda** [Azure/azure-openapi-validator#14]
The repo was earlier named and published as azure-openapi-linter and we need to take down the package from the npm feeds. Since the package was published with adx creds, we may need to go through the proper channels to have it removed.
@amarzavery might have an idea.

tagging @vishrutshah

**Comment by veronicagg** [comment]
do we really need this, or could it be marked as "deprecated"?

**Comment by amarzavery** [comment]
I unpublished 4 versions of azure-openapi-linter which means they are deleted. Can't delete the initial version. Latest version is 0.1.0 and it is marked as deprecated
