### ISSUE TITLE
Don't allow nested properties in model definitions 

### ISSUE THREAD

**Issue by vladbarosan** [Azure/azure-openapi-validator#165]
Issue here and the fix : https://github.com/haitch/azure-rest-api-specs-pr/commit/93fb7354f9389e3413e614756ba97f777c0d9dc5#diff-309e07106f19cc914923741a82e1a336R956

This causes issue with the model validation and is time confusing for code reviewers and creates the risks of issues being missed.

**Comment by jianyexi** [comment]
Already implemented by R2001 - https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#r2001
