### ISSUE TITLE
False positives for specs appearing like they have two RPs in them

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-openapi-validator#176]
For a spec that's a proxy provider for other RPs the linter thinks the spec defines multiple RPs in the same swagger which isn't the case leading to false positives.
See https://github.com/Azure/azure-rest-api-specs-pr/pull/540/ for an example.

**Comment by jhendrixMSFT** [comment]
Here's another example https://github.com/Azure/azure-rest-api-specs/pull/4058

**Comment by jianyexi** [comment]
already fixed the R3023 in this case ,  remove R2059 and Add R3030
