### ISSUE TITLE
Add a rule of checking the context in which "x-ms-pagable" extension is specified 

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-openapi-validator#178]
If `x-ms-pagable` extension applied then the return model should be really an array. 

Here is a PR for fixing a swagger with this issue https://github.com/Azure/azure-rest-api-specs/pull/4000

**Comment by annatisch** [comment]
Thanks - was just about to add this myself :)

**Comment by jianyexi** [comment]
already fixed
