### ISSUE TITLE
Where did SecurityDefinitionsStructureValidation (M2054) go?

### ISSUE THREAD

**Issue by olydis** [Azure/azure-openapi-validator#23]
It was part of my [initial template](https://github.com/olydis/azure-openapi-validator/commit/e2b62b9294dc6a945d8aea996e82829bae0989ca) for this project but neither can I find any traces of that work in the commit history nor in the code - however, it is still documented [here](https://github.com/Azure/azure-rest-api-specs/blob/35a2b0cc39a7462fd6f29f177aa2dca7f5d65b56/documentation/openapi-authoring-automated-guidelines.md). Where did it go?

**Comment by dsgouda** [comment]
You mean [this](https://github.com/Azure/autorest/blob/d693df4f717aa0aa37a31a902e33d3eb39ba2b29/src/modeler/AutoRest.Swagger/Validation/SecurityDefinitionsStructure.cs#L14) ?

**Comment by olydis** [comment]
lol, just searched for `M2054` in that repo... however, note that it's also called `M2054` in the doc!

**Comment by dsgouda** [comment]
You mean R2054, yes some of them need an update

**Comment by olydis** [comment]
well I mean `M2054` since that's what I found in the doc, but yes, apparently it has changed to `R2054` which is why I thought the rule was lost 😆

**Comment by dsgouda** [comment]
Noted.
