### ISSUE TITLE
R2056 RequiredReadOnlyProperties should be removed/disabled

### ISSUE THREAD

**Issue by jeremymeng** [Azure/azure-openapi-validator#243]
[Yesterday 3:32 PM] Johan Stenberg
    Suppress the error. While swagger 2.0 didn't allow it, the reason it didn't allow it was (IMHO) somewhat bogus. It has been addressed in openapi 3.x. 

...

[Yesterday 3:33 PM] Johan Stenberg
    In fact, I wouldn't mind someone opening an issue to disable the rule.
​[Yesterday 3:34 PM] Johan Stenberg
    Because something being required or not applies to outputs as well as for inputs.
(1 liked)​[Yesterday 3:34 PM] Johan Stenberg
    (if required means "always provided")
(2 liked)​[Yesterday 3:35 PM] Johan Stenberg
    
So unless there was another way to indicate that this data is always included in a response, it left an important gap in the expressiveness of the language.

**Comment by jianyexi** [comment]
Thanks for sharing this message. After did some investigation , our conclusion is this rule can not be disabled , as currently the SDK for python, typescript and dotnet can not handle the required readonly property correctly.
