### ISSUE TITLE
Failed to install or start extension '@microsoft.azure/classic-openapi-validator' (1.1.6)

### ISSUE THREAD

**Issue by WANdmurph** [Azure/azure-openapi-validator#245]
We're seeing an intermittent issue in our CI pipeline when attempting to install the @microsoft.azure/classic-openapi-validator node package. We have tried adding this as an explicit dependency in our package.json as a workaround, which seems to download the package but it doesn't appear to be provided through NPM at runtime to `node_modules/@microsoft.azure/extension/dist/main.js`
```
Failed to install or start extension '@microsoft.azure/classic-openapi-validator' (1.1.6)
  Error: Package '@microsoft.azure/classic-openapi-validator' - '1.1.6' failed to install:
  Failed to install package 'https://registry.npmjs.org/@microsoft.azure/classic-openapi-validator/-/classic-openapi-validator-1.1.6.tgz' -- Error: Process Failed.Error: Failed to install package 'https://registry.npmjs.org/@microsoft.azure/classic-openapi-validator/-/classic-openapi-validator-1.1.6.tgz' -- Error: Process Failed.
    at install (/node_modules/@microsoft.azure/extension/dist/main.js:303:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    ```

**Comment by jianyexi** [comment]
Did you retry installing it ?

**Comment by WANdmurph** [comment]
I think that `install (/node_modules/@microsoft.azure/extension/dist/main.js:303:15)` might be trying to install it completely independently of npm managed packages? we added it as an explicit dependency in our project and it would install successfully via `npm install` (which has retries configured) but would still fail at this step

**Comment by jianyexi** [comment]
it should be fixed in the latest version
