### ISSUE TITLE
Support new format `arm-id` and associated extension `x-ms-arm-id-details`

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-openapi-validator#265]
This annotation was [proposed and accepted](https://github.com/Azure/autorest/pull/4150) recently.

I then attempted to use it in [various service Swaggers](https://github.com/Azure/azure-rest-api-specs/pull/18318) but realized that it is causing the validator to fail.

Would it be possible to add support for this format and annotation? Filing this at the mention of @leni-msft

**Comment by leni-msft** [comment]
@jianyexi pls help check
