### ISSUE TITLE
Crash for provider operations list when using common-types

### ISSUE THREAD

**Issue by bryan-strassner** [Azure/azure-openapi-validator#269]
**Describe the bug**
(Redirected here from: [https://github.com/Azure/autorest/issues/4489](https://github.com/Azure/autorest/issues/4489))

When using autorest to validate our RP's swagger, the Autorest program is crashing unexpectedly while validating a `/providers/Microsoft.RPName/operations` path that:

* Uses a reference to common-types (that are copied locally and successfully used in other parts of the swagger
* Is returning a `200` response
* Has `x-ms-pageable` specified

**I have a minimal example**:

_"ex.json"_

```json
{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A simple sample",
    "title": "simple",
    "version": "2022-03-17-preview"
  },
  "host": "management.azure.com",
  "paths": {
    "/providers/Microsoft.SimpleSample/operations": {
      "get": {
        "description": "Get a list of all available resource provider operations. It contains a URL link to get the next set of results.",
        "summary": "List resource provider operations.",
        "operationId": "Operations_List",
        "parameters": [
          {
            "$ref": "./types.json#/parameters/ApiVersionParameter"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "./types.json#/parameters/OperationListResult"
              
            }
          },
          "default": {
            "description": "Error response describing why the operation failed.",
            "schema": {
              "$ref": "./types.json#/definitions/ErrorResponse"
            }
          }
        },
        "x-ms-pageable": {
          "nextLinkName": "nextLink"
        }
      }
    }
  },
  "definitions" : {
    "SomethingLocal": {
      "type": "object",
      "title": "lorem ipsum",
      "properties": {
        "value": {
          "description": "Lorem Ipsum",
          "type": "array",
          "items": {
            "$ref": "./types.json#/definitions/ErrorResponse"
          }
        },
        "nextLink": {
          "description": "The next link",
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "azure_auth": {
        "description": "Azure Active Directory OAuth2 Flow",
        "type": "oauth2",
        "flow": "implicit",
        "authorizationUrl": "https://login.microsoftonline.com/common/oauth2/authorize",
        "scopes": {
          "user_impersonation": "impersonate your user account"
        }
    }
  },
  "security": [
    {
      "azure_auth": [
        "user_impersonation"
      ]
    }
  ]
}

```

**The stack trace**:

```
fatal   | System.ArgumentException: Reference path 'OperationListResult' does not exist in the definition section of the Swagger document.
   at OpenAPI.Validator.SchemaResolver.DereferenceInner(String referencePath, List`1 visitedReferences)
   at OpenAPI.Validator.SchemaResolver.Unwrap(Schema schema)
   at OpenAPI.Validator.Validation.Extensions.PageableRequires200Response.IsValid(Object pageable, RuleContext context)
  ...
```

**When run using**:

```
autorest --input-file=./ex.json --validation --azure-validator --version=3.7.6
```

_Note: same results for --version=3.6.4 and --version=3.8.0_

_Note: yes, the common-types are available in the local environment at the paths specified_

**What prevents the crash**:

* Changing the response to any code other than `200`
* Removing the `x-ms-pageable` definition.
* declaring the common-types/v2/types.json#/definitions/OperationListResult as a local type instead. (e.g., "SomethingLocal" in the example)
* omitting --version (runs with ~2.0.4413)

Wondering if:  `OpenAPI.Validator.Validation.Extensions.PageableRequires200Response.IsValid` is not liking the remote file reference?

**A few notes**
* We have encountered this error as well at the beginning of every run, but then validation runs "fine" besides
```
fatal   | Failed validating: 'file:///home/bstrassner/aods/nc-rp/api/ex.json', error encountered: TypeError: Cannot read properties of undefined (reading 'properties')
```
* We are using WSL2 / Ubuntu as our development environment
* We have not figured out how to prevent the validator from issuing errors against the Azure common types `types.json` file that it references.

**Finally the question**:
What is the expected behavior or configuration that I'm missing here? I'd like to appropriately reference common-types, and I'd like to validate locally using autorest, but this makes our gating fail.

**Expected behavior**
Be able to add x-ms-pageable and reference common-types at the same time for a 200 response.

Attached is a shortened version of "types.json", but our testing is with the standard common types found here:
[https://github.com/Azure/azure-rest-api-specs-pr/blob/RPSaaSDev/specification/common-types/resource-management/v2/types.json](https://github.com/Azure/azure-rest-api-specs-pr/blob/RPSaaSDev/specification/common-types/resource-management/v2/types.json)

**Attachments**
An abbreviated types.json: [types.json.txt](https://github.com/Azure/azure-openapi-validator/files/8367363/types.json.txt)
Run log with stack trace: [runLog.txt](https://github.com/Azure/azure-openapi-validator/files/8367400/runLog.txt)
run log with local reference: [runLogLocalType.txt](https://github.com/Azure/azure-openapi-validator/files/8367405/runLogLocalType.txt)

**Comment by jianyexi** [comment]
Good catch, the systemData is optional now, so this rule will be retired
