### ISSUE TITLE
SystemData is reported as invalid property at top level

### ISSUE THREAD

**Issue by mvvsubbu** [Azure/azure-openapi-validator#272]
As per ARM guidelines we are including SystemData for our new resource but the azure-validator is throwing this as invalid property

https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-contracts.md 

d:\Proxies>autoRest D:\Repos\azure-rest-api-specs-pr\specification\databricks\resource-manager\readme.md --azure-validator=true >output.log
ERROR (BodyTopLevelProperties/R3006/ARMViolation): Top level properties should be one of name, type, id, location, properties, tags, plan, sku, etag, managedBy, identity, zones. Model definition 'Workspace' has extra properties ['systemData'].
- file:///D:/Repos/azure-rest-api-specs-pr/specification/databricks/resource-manager/Microsoft.Databricks/preview/2022-08-01-preview/databricks.json:702:6 ($.definitions.Workspace.properties)
ERROR (BodyTopLevelProperties/R3006/ARMViolation): Top level properties should be one of name, type, id, location, properties, tags, plan, sku, etag, managedBy, identity, zones. Model definition 'AccessConnector' has extra properties ['systemData'].
- file:///D:/Repos/azure-rest-api-specs-pr/specification/databricks/resource-manager/Microsoft.Databricks/preview/2022-08-01-preview/accessconnector.json:311:6 ($.definitions.AccessConnector.properties)

**Comment by jianyexi** [comment]
you should use the latest validator , see https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/ci-fix.md#given-a-readme-file-run-linter
