### ISSUE TITLE
TrackedResourcePatchOperation - update message and documentation

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-openapi-validator#30]
The message for this rule is currently: "Tracked resource '{0}' must have patch operation that at least supports the update of tags." 
It looks like some RPs are following just this, therefore there may create a PATCH operation for update of tags and call it "Update", as well as have another operation which is "CreateOrUpdate" done with a PUT. Having an operation called "Update" that only allows the update of tags, seems misleading for the user. ARM still wants to have a PATCH operation for tags, at least. 
So, the current recommendation is, let's update the message of this rule, to recommend having all mutable properties included in the PATCH operation, which would make the "Update" a real 'update'. For new RPs/services, we'd like this to be the case, for older cases, we may need to have folks still call it "Update" or "UpdateTags" to be more explicit (just note that if UpdateTags is chosen, it'll most likely be a breaking changes once the PATCH starts supporting other mutable properties).
Suggested message:
"Tracked resource '{0}' must have patch operation that at least supports the update of tags. It's strongly recommended that the PATCH operation supports update of all mutable properties as well."
Please update the documentation for this rule as well (https://github.com/Azure/azure-rest-api-specs/blob/current/documentation/openapi-authoring-automated-guidelines.md#r3026-trackedresourcepatchoperation) to update the message and include the consequences, basically:
Impact on generated code: If PATCH operation only supports the update of tags and it's called "Update", there may be a "CreateOrUpdate" (if there's a PUT operation already called this way for update purposes) and an "Update" method in the generated SDK, where "Update" would be just for the update of tags, making it a less desired user experience. Please strongly consider adding all mutable properties to the "Update" operation, or modify the name of the operation if desired (ex. "UpdateTags")

**Comment by veronicagg** [comment]
@salameer @johanste @ravbhatnagar @kirthik Please review the above, and confirm message and documentation update text.

**Comment by salameer** [comment]
I'm good here

**Comment by johanste** [comment]
Looks good. I was considering mentioning if-match/etags in the context of a PATCH:less operation (if you support neither PATCH nor if-match/etags, it is impossible for a client to avoid conflicts on update operations). But I don't want users to have to read a whole book when going through the error messages :)

**Comment by ravbhatnagar** [comment]
Looks fine. One thing - "...or modify the name of the operation if desired (ex. "UpdateTags")" - Wont this likely break clients when service teams progressively adds support for patching more properties. Then the name would need to be updated.

**Comment by veronicagg** [comment]
@ravbhatnagar yes, that change in operation name would break clients if service adds more properties, that's the reason I added it as an 'or' to updating the operation to include more properties. I think I'll remove that part and we can live with the operation begin called "Update" even if it's somewhat confusing at the time.
