### ISSUE TITLE
Invalid Input for openapi-type: data-plane. Valid values are 'arm', 'data-plane' or 'default'.

### ISSUE THREAD

**Issue by olydis** [Azure/azure-openapi-validator#33]
Cause: the enum parse fails since there's no dash in the enum value.
My fix [here](https://github.com/Azure/autorest/pull/2426/files#diff-7cbb9d1e00f17632bc539a6a200a711aR87) or something equivalent has to be applied here, too (now that I look at it, also make "Input" lower case)

**Comment by dsgouda** [comment]
@olydis, Looks like you merged the fix, feel free to reopen if necessary.

**Comment by olydis** [comment]
huh? I did fix it in the AutoRest repo, but not in here!

**Comment by olydis** [comment]
or have you fixed the issue as part of your extraction?

**Comment by dsgouda** [comment]
D'oh I will reflect it in the validator repo
