### ISSUE TITLE
[new rule]: Async PATCH should return 202.

### ISSUE THREAD

**Issue by jianyexi** [Azure/azure-openapi-validator#335]
### Lint rule description

Async PATCH should return 202.

### Related swagger example

N

### Category

ARM

### Severity level

Error

### Applies to

Management plane API spec, RPaaS API spec

### How to fix the violation

avoid using 201 as async response code

### What't the impact if breaking the rule

ARM guideline

**Comment by TimLovellSmith** [comment]
I thought it would be supposed return 201 Created for RPs which want to allow PATCH to do Create? And provisioningState should be required in response when they do?
[Is PATCH really allowed to do create??]
