### ISSUE TITLE
[new rule]: Give errors when unused schema is detected

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-openapi-validator#339]
### Lint rule description

We should give error if a swagger contains schemas that are not used anywhere inside this swagger file or across all the swagger files inside the same directory?

### Related swagger example

1. https://github.com/Azure/azure-rest-api-specs/blob/main/specification/orbital/resource-manager/Microsoft.Orbital/stable/2022-03-01/orbital.json#L1352-L1367
2. https://github.com/Azure/azure-rest-api-specs/blob/main/specification/orbital/resource-manager/Microsoft.Orbital/stable/2022-03-01/orbital.json#L2115-L2129
The Status schema with small s is not used in this swagger, and it causes duplicate schema

### Category

SDK

### Severity level

Error

### Applies to

Management plane API spec, Data plane API spec, RPaaS API spec

### How to fix the violation

Remove the reported schemas

### What't the impact if breaking the rule

First it might introduce duplicate schemas in modeler v4, and this will cause the SDK generation to fail.
If it passes, 
1. some unnecessary merging of schemas might happen inside M4, and results in some wrong descriptions (see the example above)
2. an unused model will be introduced in SDK, and if the SDK keep that, it is very likely to introduce unnecessary breaking changes to our SDK

**Comment by jianyexi** [comment]
this seems duplicated with https://github.com/Azure/azure-openapi-validator/issues/311

**Comment by ArcturusZhang** [comment]
> this seems duplicated with #311

Good to know. Let us follow up this new rule on that issue
