### ISSUE TITLE
Write documentation for OperationIdNounConflictingModelNames and ParameterizeProperties

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-openapi-validator#34]
Need to write documentation for OperationIdNounConflictingModelNames and ParameterizeProperties since these are still in production.
Ref: https://github.com/Azure/autorest/issues/2346

**Comment by dsgouda** [comment]
Documentation has been added.

**Comment by veronicagg** [comment]
https://github.com/Azure/azure-rest-api-specs/commit/35a2b0cc39a7462fd6f29f177aa2dca7f5d65b56
