### ISSUE TITLE
'url' is the same as 'uri' 

### ISSUE THREAD

**Issue by jianyexi** [Azure/azure-openapi-validator#345]
should flag 'url' as known format

**Comment by archerzz** [comment]
I suggest sticking to `uri`, since it's in swagger document, and all definitions under `parameters` only allow `uri`. We could make an exception for parameter definitions under `x-ms-parameterized-host`, because it exists for quite a long time.

**Comment by jianyexi** [comment]
I think the problem is M4 supports 'url' for long time, @lmazuel do you think we need to switch to 'uri' in the future ?

**Comment by lmazuel** [comment]
Just to be clear, none of `url` or `uri` exists in the Swagger, this is all added by us in our SDK team. Right now we have an inconsistency, where m4 accepts only `url` and linter accepts only `uri`. Which means service team might use `uri` to get the linter happy and have no codegen support, or use `url` with a suppression and get codegen.

The simplest way to me is to support both in both places as equivalent.

**Comment by jianyexi** [comment]
@lmazuel thanks for clarification, for this rule https://github.com/Azure/azure-openapi-validator/issues/303, we need to guide user to use the 'url' not uri, right?
