### ISSUE TITLE
Write documentation for the following set of rules: LongRunningResponseStatusCode, ResourceHasXMsResourceEnabled

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-openapi-validator#35]
Please refer to details at https://github.com/Azure/autorest/issues/2347.

**Comment by veronicagg** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/1337

**Comment by sarangan12** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/1472

**Comment by sarangan12** [comment]
Task Completed
