### ISSUE TITLE
[new rule]: Add a linter rule to ask the author to define a regex for resource names

### ISSUE THREAD

**Issue by rkmanda** [Azure/azure-openapi-validator#357]
### Lint rule description

It is widely observed that resource names have restrictions but dont define what these restrictions are in the swagger. This rule will ensure that the authors explicitly define these restrictions as a regex on the resource name. If a team does not have custom rules then the ARM's default rule should get applied.

### Related swagger example

I dont have an example

### Category

ARM

### Severity level

Error

### Applies to

Management plane API spec, RPaaS API spec

### How to fix the violation

Define a regex for the resource names

### What't the impact if breaking the rule

The problems
1.	There are currently more than 4000 resources that do not specify their name constraints in the swagger.
2.	Most of the products do not comply to the default limit and many of them have a different limit in the description of the resources but even so do not specify formal constraints
3.	If a product does work with today default constrains for name that does not mean that it will comply with the constraints if they change in the future.
4.	Testing the name constrains in the current environment will be onerous since it would require try to create a resource for each one of the possible name corner cases and check if it would return an error. If the resource takes long to create this could take hours.

**Comment by jianyexi** [comment]
@rkmanda  do you know the ARM default rule for resource name ?  see https://github.com/Azure/azure-openapi-validator/issues/393
