### ISSUE TITLE
LintDiff error with no indication of possible fix

### ISSUE THREAD

**Issue by Selekena** [Azure/azure-openapi-validator#374]
My PR (https://github.com/Azure/azure-rest-api-specs/pull/20134/checks?check_run_id=7840467413) received this error during the lintdiff validation. I am not sure what is wrong where and what the fix is from my swagger change. 

Please advise.

Error logs: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1781443&view=logs&j=0574a2a6-2d0a-5ec6-40e4-4c6e2f70bea2&t=80c3e782-49f0-5d1c-70dd-cbee57bdd0c7&l=2184

error preview: 

LintDiff error log ----
--- Errors of Lint Diff (formated) ----

[
  {
    "type": "AutoRest exception",
    "message": "swagger-document/individual/schema-validator - FAILED",
    "readme": "specification/deviceprovisioningservices/resource-manager/readme.md",
    "readmeUrl": "[https://github.com/Azure/azure-rest-api-specs/blob/19e99a668acfc98867608d96b11b07268ebb7594/specification/deviceprovisioningservices/resource-manager/readme.md",](https://github.com/Azure/azure-rest-api-specs/blob/19e99a668acfc98867608d96b11b07268ebb7594/specification/deviceprovisioningservices/resource-manager/readme.md%22,)
    "tag": "package-preview-2022-08",
    "context": "after"
  },
  {
    "type": "AutoRest exception",
    "message": "Error: [OperationAbortedException] Error occurred. Exiting.",
    "readme": "specification/deviceprovisioningservices/resource-manager/readme.md",
    "readmeUrl": "[https://github.com/Azure/azure-rest-api-specs/blob/19e99a668acfc98867608d96b11b07268ebb7594/specification/deviceprovisioningservices/resource-manager/readme.md",](https://github.com/Azure/azure-rest-api-specs/blob/19e99a668acfc98867608d96b11b07268ebb7594/specification/deviceprovisioningservices/resource-manager/readme.md%22,)
    "tag": "package-preview-2022-08",
    "context": "after"
  }
]

**Comment by jianyexi** [comment]
this is because there are schema validator errors in your swagger which means your swagger contains some invalid semantic
