### ISSUE TITLE
[NoDuplicatePathsForScopeParameter] - false positive

### ISSUE THREAD

**Issue by ms-zhenhua** [Azure/azure-openapi-validator#543]
**Describe the bug**
`/{scope}/providers/Microsoft.Security/customRecommendations/{customRecommendationName}` and `/{scope}/providers/Microsoft.Security/customRecommendations` are identified as duplicated paths.

**To Reproduce**
https://github.com/Azure/azure-rest-api-specs/pull/24090/checks?check_run_id=13899786994

**Expected behavior**
Should not report this error.

**Screenshots**
![image](https://github.com/Azure/azure-openapi-validator/assets/76987228/7ac0aa8b-f588-4a60-a0be-767c90debc7f)

**Comment by bdefoy** [comment]
Tracking with https://msazure.visualstudio.com/One/_workitems/edit/24906300.
