### ISSUE TITLE
False Alarm for PropertiesTypeObjectNoDefinition

### ISSUE THREAD

**Issue by ms-zhenhua** [Azure/azure-openapi-validator#611]
**Describe the bug**
LintDiff validates object properties with valid references as PropertiesTypeObjectNoDefinition error

**To Reproduce**
https://github.com/Azure/azure-rest-api-specs/pull/26059/checks?check_run_id=17364203013
https://github.com/Azure/azure-rest-api-specs/pull/26074/checks?check_run_id=17373809665

**Expected behavior**
These properties are valid

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mikeharder** [comment]
Possibly fixed or mitigated by #643

**Comment by FumingZhang** [comment]
Got another false alert https://github.com/Azure/azure-rest-api-specs/pull/30395/checks?check_run_id=29708193221

**Comment by mikeharder** [comment]
@tejaswiMinnu: Another rule that needs to be re-disabled, that was accidentally re-enabled here:

https://github.com/Azure/azure-openapi-validator/pull/733/files#diff-2c4dbe936f4558f78f5611dc25eaba744271ce8a45191f1d92143dbd653be0cfL3357

**Comment by mikeharder** [comment]
Re-disabled in #740
