### ISSUE TITLE
Rule for x-ms-enum crashes when "name" property is missing.

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-openapi-validator#654]
The following Swagger causes LintDiff to crash with a fatal error:
![image](https://github.com/Azure/azure-openapi-validator/assets/5723682/ef57f9e8-eb6c-48b3-b364-dd0bbdb43aaf)

The error is:
`openapiValidatorPluginFunc: Failed validating:TypeError: Cannot read property 'toLowerCase' of undefined
Location`

Here's the failing CI run:
https://github.com/Azure/azure-rest-api-specs/pull/27356/checks?check_run_id=20396982945

Per the [specification for x-ms-enum](https://azure.github.io/autorest/extensions/#x-ms-enum), `name` is an optional field, so any rule that is operating on `x-ms-enum` needs to have appropriate logic. In this case, the rule seems to be assuming name exists and calling `toLowerCase` on it, resulting in the fatal crash.

**Comment by mikeharder** [comment]
Related to https://github.com/Azure/azure-sdk-tools/issues/7602

**Comment by mikeharder** [comment]
I this this code just needs to no-op if `name` is undefinted:

https://github.com/Azure/azure-openapi-validator/blob/2fbba6df729ed434089a9cc62b351171772fee01/packages/rulesets/src/native/legacyRules/UniqueXmsEnumName.ts#L23-L24

**Comment by konrad-jamrozik** [comment]
Yeah so probably, in pseudocode:

> if (section.value["x-ms-enum"] && isValidEnum(section.value)) { 

-->

> if (section.value["x-ms-enum"] && isValidEnum(section.value) && section.value["x-ms-enum"] is defined) {

**Comment by mikeharder** [comment]
> if (section.value["x-ms-enum"] && isValidEnum(section.value) && section.value["x-ms-enum"].name is defined) {

Need to check if `name` is defined

**Comment by konrad-jamrozik** [comment]
Should be fixed now.

**Comment by mikeharder** [comment]
Swagger LintDiff is now passing for https://github.com/Azure/azure-rest-api-specs/pull/27356.
