### ISSUE TITLE
LintDiff Process canceled due to failure could not read file

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-openapi-validator#673]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [ ] have you checked existing issues

**Describe the bug**

Automatic LintDiff continuous integration is giving errors in the following PR.

https://github.com/Azure/azure-rest-api-specs-pr/pull/16988

❌ AutoRest exception | "tag":"default","details":"Process() cancelled due to failure" |  
❌ AutoRest exception | "tag":"default","details":"!Error: Could not read 'file:///mnt/vss/_work/1/azure-rest-api-specs-pr/specification/windowsesu/resource-manager/Microsoft.WindowsESU/preview/2019-09-16/windowsesu.json'." |  
❌ AutoRest exception | "tag":"default","details":"Autorest completed with an error. If you think the error message is unclear,or is a bug,please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing."

```
Please provide as much information as you can. This would be:
- OpenAPI files having the issues
- Autorest command used
```

**Expected behavior**
It should instead give normal linter output shouldn't it? At least the file looks to be part of the PR.

**Additional context**
[must fix]The following errors/warnings are introduced by current PR

**Comment by mikeharder** [comment]
The first issue was a bug in the spec:

https://github.com/Azure/azure-rest-api-specs-pr/blob/983cac0c78ad3f65ea4ce550da1f0e05de108856/specification/windowsesu/resource-manager/readme.md?plain=1#L38

`readme.md` pointed to an input file that did not exist.

**Comment by mikeharder** [comment]
@renesc-ms: Your spec has a similar bug and was already merged to RPSaaSDev.

https://github.com/Azure/azure-rest-api-specs-pr/blob/8ee60dd313c05717d1c291256405bb1d598354a9/specification/supplychain/resource-manager/readme.md#L38

Your `readme.md` points to an input file that doesn't exist.  The version should be `2023-02-22-preview` instead of `2023-02-22`.

**Comment by renesc-ms** [comment]
@mikeharder Thank you for your follow-up which clarifies the issue for us to address.
