### ISSUE TITLE
Consider upgrading common-types to v6

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-openapi-validator#734]
v6 common types were added in this PR:
 
https://github.com/Azure/azure-rest-api-specs/pull/29155
 
But azure-openapi-validator was not updated to match:
 
https://github.com/Azure/azure-openapi-validator/blob/3f5b0c26d46995e23918f74c07d60df24d8a86fd/packages/rulesets/src/spectral/functions/utils.ts#L3-L11

Should it be?

**Comment by tejaswiMinnu** [comment]
PR - https://github.com/Azure/azure-openapi-validator/pull/735
