### ISSUE TITLE
PutRequestResponseScheme has potentially incomplete warning message

### ISSUE THREAD

**Issue by dsgouda** [Azure/azure-openapi-validator#74]
Per the documentation [here](https://github.com/Azure/azure-rest-api-specs/blob/current/documentation/openapi-authoring-automated-guidelines.md#R2017), when the PUT request and response objects do not match we recommend adding a PATCH operation. However there are no guidelines about what the PATCH request and response models should be in order to address this issue.

**Comment by sarangan12** [comment]
Closing this for now
