### ISSUE TITLE
Move documentation out of Autorest

### ISSUE THREAD

**Issue by dsgouda** [Azure/azure-openapi-validator#78]
Some validation related seems to be lying around in AutoRest today
[Here](https://github.com/Azure/autorest/blob/master/docs/developer/guide/writing-validation-rules.md) for instance, we should take out some time to clean up this and decide if these instructions need to be modified in the context of this repo.

**Comment by sarangan12** [comment]
Seems already done https://github.com/Azure/azure-openapi-validator/blob/master/docs/developer/authoring-new-validation-rules.md. CLosing this now
