### ISSUE TITLE
New rule: verify the parameters defined in the global parameters section

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-openapi-validator#84]
Autorest treats the parameters defined in the global parameters section as client properties. Hence one needs to be super sure when they are adding a parameter over there.

90% scenario is that subscriptionId and api-version are parameters that should be defined in the lobal parameters section.

However, one can define a parameter that is being referenced in multiple operations (example: resourceGroupName) in the global parameters section and apply the extension `"x-ms-parameter-location": "method"`. This will then not be a client property.

It would be nice to have a linter rule that validates this aspect and warns the user. 

[CognitiveSerivices api has location as a global parameter](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/2017-04-18/cognitiveservices.json#L1032) and SDKs have shipped with this. It seems odd to pass location while instantiating the client.

**Comment by amarzavery** [comment]
Another instance that proves that this should definitely be a linter rule.
(someone added resourceGroupName and expressRouteConnectorName as global parameters and the reviewer merged it)[https://github.com/Azure/azure-rest-api-specs-pr/pull/89/files#diff-97646710ea82ab92a7c2fcdae470581bR460]. By having this linter rule we will make it easier for reviewers.

**Comment by amarzavery** [comment]
And one more PR in the management plane was merged incorrectly https://github.com/Azure/azure-rest-api-specs/commit/bc175dbf36fd6d8e4ccac18a3bfd102d43fc6672#diff-e895aa4ceab43a039f4baf6e7b2bf7c0R3146

**Comment by lmazuel** [comment]
Another example: https://github.com/Azure/azure-rest-api-specs/pull/1829

**Comment by lmazuel** [comment]
New example: https://github.com/Azure/azure-rest-api-specs/pull/1860

**Comment by lmazuel** [comment]
Another example of merged PR:
https://github.com/Azure/azure-rest-api-specs-pr/pull/263/files#diff-ab59bbd9ab18efab6f5800473e0d7bb6R720

**Comment by mboersma** [comment]
Apparently I got bitten by this issue as well in https://github.com/Azure/azure-cli/pull/5086 but luckily @lmazuel is watching out for this. 

Adding a linter to rule to catch this in the future would be 💯.

**Comment by lmazuel** [comment]
Again: https://github.com/Azure/azure-rest-api-specs/pull/2052

**Comment by lmazuel** [comment]
@salameer At some point we need to prioritize this, this is really time-consuming... :(

**Comment by salameer** [comment]
@veronicagg @sarangan12 @mcardosos 

THis seems to be a rule that benefits our group and it's efficiency can we please prioritize this?

**Comment by veronicagg** [comment]
@salameer I've just tagged it with Sprint-113. We haven't been updating rules recently or scheduling any work for them, it'd be good to triage and select which ones we'd like to tackle next and how it prioritizes with other work.

**Comment by salameer** [comment]
Lets Focus on SDK rules only

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lmazuel** [comment]
Again https://github.com/Azure/azure-rest-api-specs/pull/2289

**Comment by amarzavery** [comment]
For Heaven's sake, please implement this linter rule. 
This [Consumption API PR](https://github.com/Azure/azure-rest-api-specs/pull/2335/files#diff-823b312a7b7d9f3c3c976f374ba46fbcR2070) was merged incorrectly. It has resourceGroupName and budgetName as client properties. They should be method parameters.
Assign this issue on priority to someone and implement this linter rule.
/cc @salameer

**Comment by lmazuel** [comment]
Again https://github.com/Azure/azure-rest-api-specs/pull/2433

**Comment by lmazuel** [comment]
Seriously, now when I type "validator" in my Chrome bar, it suggest me directly this issue....

**Comment by lmazuel** [comment]
Again https://github.com/Azure/azure-rest-api-specs/pull/2391

**Comment by sarangan12** [comment]
The new Rule [XmsParameterLocation](https://github.com/Azure/azure-openapi-validator/blob/master/src/dotnet/OpenAPI.Validator/Validation/XmsParameterLocation.cs) has been implemented.  Refer [PR #149](https://github.com/Azure/azure-openapi-validator/pull/149) for details. 

The dotnet classic open api validator is scheduled for release on Monday, March 19, 2018. The code changes are complete. Refer [PR #150][https://github.com/Azure/azure-openapi-validator/pull/150] for further details. 

All the existing errors have already been fixed in the specs repository. Refer [PR #2649](https://github.com/Azure/azure-rest-api-specs/pull/2649) for details.

There is no pending action items (of course the actual release is pending until 19th) in this issue. Resolving it now.
